<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-PV3D5P9" name="listeners.Configuration" tests="12" failures="1" timestamp="08 Sep 2018 10:20:27 GMT" time="0.047" errors="0">
  <testcase name="test3" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test3" time="0.000" classname="listeners.Configuration">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test3" time="0.000" classname="listeners.Configuration">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test3" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test3" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test1" time="0.015" classname="listeners.Configuration">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test3" time="0.000" classname="listeners.Configuration"/>
  <testcase name="test1" time="0.000" classname="listeners.Configuration">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.016" classname="listeners.Configuration">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at listeners.Configuration.test1(Configuration.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.016" classname="listeners.Configuration">
    <skipped/>
  </testcase> <!-- test1 -->
</testsuite> <!-- listeners.Configuration -->
